// <auto-generated />
using System;
using IncidentApp.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IncidentApp.Model.Migrations
{
    [DbContext(typeof(IncidentAppContext))]
    [Migration("20201130021235_config")]
    partial class config
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IncidentApp.Model.Model.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Borrado")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("CreadoPor");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2020, 11, 29, 22, 12, 35, 419, DateTimeKind.Local));

                    b.Property<int>("ModificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("DepartamentoId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("IncidentApp.Model.Model.HistorialIncidente", b =>
                {
                    b.Property<int>("HistorialIncidenteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Borrado");

                    b.Property<string>("Comentario");

                    b.Property<int>("CreadoPor");

                    b.Property<string>("Estatus");

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<DateTime>("FechaRegistro");

                    b.Property<int>("IncidenteId");

                    b.Property<int>("ModificadoPor");

                    b.HasKey("HistorialIncidenteId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("HistorialIncidente");
                });

            modelBuilder.Entity("IncidentApp.Model.Model.Incidente", b =>
                {
                    b.Property<int>("IncidenteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Borrado")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("CoemntarioCierrre")
                        .HasMaxLength(500);

                    b.Property<int>("CreadoPor");

                    b.Property<int>("DepartamentoId");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<DateTime>("FechaCierre");

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2020, 11, 29, 22, 12, 35, 483, DateTimeKind.Local));

                    b.Property<int>("ModificadoPor");

                    b.Property<int>("PrioridadId");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("UsuarioAsignadoId");

                    b.Property<int>("UsuarioReportaId");

                    b.HasKey("IncidenteId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("ModificadoPor");

                    b.HasIndex("PrioridadId");

                    b.HasIndex("UsuarioAsignadoId");

                    b.HasIndex("UsuarioReportaId");

                    b.ToTable("Incidente");
                });

            modelBuilder.Entity("IncidentApp.Model.Model.Prioridad", b =>
                {
                    b.Property<int>("PrioridadId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Borrado")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("CreadoPor");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2020, 11, 29, 22, 12, 35, 478, DateTimeKind.Local));

                    b.Property<int>("ModificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("SlaId");

                    b.HasKey("PrioridadId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.HasIndex("SlaId");

                    b.ToTable("Prioridad");
                });

            modelBuilder.Entity("IncidentApp.Model.Model.Puesto", b =>
                {
                    b.Property<int>("PuestoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Borrado")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("CreadoPor");

                    b.Property<int>("DepartamentoId");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2020, 11, 29, 22, 12, 35, 422, DateTimeKind.Local));

                    b.Property<int>("ModificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("PuestoId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("Puesto");
                });

            modelBuilder.Entity("IncidentApp.Model.Model.Sla", b =>
                {
                    b.Property<int>("SlaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Borrado")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("CantdadHoras");

                    b.Property<int>("CreadoPor");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2020, 11, 29, 22, 12, 35, 475, DateTimeKind.Local));

                    b.Property<int>("ModificadoPor");

                    b.HasKey("SlaId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("Sla");
                });

            modelBuilder.Entity("IncidentApp.Model.Model.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Borrado")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("CreadoPor");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<DateTime>("FechaModificacion");

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2020, 11, 29, 22, 12, 35, 434, DateTimeKind.Local));

                    b.Property<int>("ModificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("PuestoID");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15);

                    b.HasKey("UsuarioId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.HasIndex("PuestoID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("IncidentApp.Model.Model.Departamento", b =>
                {
                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioC")
                        .WithMany("DepartamentosC")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioM")
                        .WithMany("DepartamentosM")
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IncidentApp.Model.Model.HistorialIncidente", b =>
                {
                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioC")
                        .WithMany("HistorialIncidentesC")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Incidente", "Incidente")
                        .WithMany()
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioM")
                        .WithMany("HistorialIncidentesM")
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IncidentApp.Model.Model.Incidente", b =>
                {
                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioC")
                        .WithMany("IncidentesC")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Departamento", "Departamento")
                        .WithMany("Incidentes")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioM")
                        .WithMany("IncidentesM")
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Prioridad", "Prioridad")
                        .WithMany("Incidentes")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioA")
                        .WithMany("IncidentesA")
                        .HasForeignKey("UsuarioAsignadoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioR")
                        .WithMany("IncidentesR")
                        .HasForeignKey("UsuarioReportaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IncidentApp.Model.Model.Prioridad", b =>
                {
                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioC")
                        .WithMany("PrioridadesC")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioM")
                        .WithMany("PrioridadesM")
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Sla", "Sla")
                        .WithMany("Prioridades")
                        .HasForeignKey("SlaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IncidentApp.Model.Model.Puesto", b =>
                {
                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioC")
                        .WithMany("PuestosC")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Departamento", "Departamento")
                        .WithMany("Puestos")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioM")
                        .WithMany("PuestosM")
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IncidentApp.Model.Model.Sla", b =>
                {
                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioC")
                        .WithMany("SlasC")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioM")
                        .WithMany("SlasM")
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IncidentApp.Model.Model.Usuario", b =>
                {
                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioC")
                        .WithMany("IUsuariosC")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Usuario", "UsuarioM")
                        .WithMany("IUsuariosM")
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentApp.Model.Model.Puesto", "Puesto")
                        .WithMany("Usuarios")
                        .HasForeignKey("PuestoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
